name: publications

on:
  workflow_dispatch:
  #schedule:
  #  - cron:  '30 17 * * 0'

jobs:
  generate-publications:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: '3.8' 
      - run: |
           python -m pip install --upgrade pip
           pip install pipenv          
           pipenv install

      - name: Generate publications
        run: |
          make publications
