name: publications

env:
  HUGO_VERSION: "0.79.1"

on:
  workflow_dispatch:
  #schedule:
  #  - cron:  '30 17 * * 0'

jobs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install pipenv
        run: |
           python -m pip install --upgrade pip
           pip install pipenv          
        
      - name: Install dependencies with pipenv
        run: |
           pipenv install

      - name: Generate publications
        run: |
          make publications
