name: seclab-CI

env:
  HUGO_VERSION: "0.79.1"

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 17 * * 0'

jobs:
  build:
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      python-version: ["3.9"]
  #      pipenv-version: ["v2022.9.21"]
  #      os: [ubuntu-20.04] #, ubuntu-latest]
    #runs-on: ${{ matrix.os }}
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
            python-version: '3.8' 
      - run: |
           python -m pip install --upgrade pip
           pip install pipenv          
           pipenv install

      - name: Generate publications
        run: |
          make publications
          
      - name: Cache hugo
        uses: actions/cache@v2
        env:
          cache-name: cache-hugo-${{ env.HUGO_VERSION }}
        with:
          path: hugo
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install hugo
        run:
          wget -q https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.tar.gz -O - | tar xz hugo    
      
      #- name: Prepare worktree
      #  run:
      #    git worktree add --track -b gh-pages public origin/gh-pages

      - name: Clear generated publications directory in case of deletions
        run:
          find public/publications -mindepth 1 -delete || true

      - name: Generate website
        run:
          make generate

      #- name: Publish public
      #  run: |
      #    cd public
      #    git config --local user.email "action@github.com"
      #    git config --local user.name "GitHub Action"
      #    (git add --all . && git commit -m "Publish changes" -a && git push origin gh-pages) || true;
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2      
