name: CI

env:
  HUGO_VERSION: "0.79.1"

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 17 * * 0'
  push:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        pipenv-version: ["v2022.9.21"]
        os: [ubuntu-20.04] #, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install pipenv
        run: |
           python -m pip install --upgrade pip
           pip install pipenv          
        
      - name: Install dependencies with pipenv
        run: |
           pipenv install

      - name: Generate publications
        run: |
          make publications
          
      - name: Cache hugo
        uses: actions/cache@v2
        env:
          cache-name: cache-hugo-${{ env.HUGO_VERSION }}
        with:
          path: hugo
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install hugo
        run:
          wget -q https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_${{ env.HUGO_VERSION }}_Linux-64bit.tar.gz -O - | tar xz hugo    
      
      - name: Prepare worktree
        run:
          git worktree add --track -b gh-pages public origin/gh-pages

      - name: Clear generated publications directory in case of deletions
        run:
          find public/publications -mindepth 1 -delete || true

      - name: Generate website
        run:
          make generate

      - name: Publish public
        run: |
          cd public
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          (git add --all . && git commit -m "Publish changes" -a && git push origin gh-pages) || true;
